version: "3.9"
services:
  cpggen:
    image: ghcr.io/appthreat/cpggen:main
    ports:
      - "7072:7072"
    volumes:
      - /home/almalinux/work:/app # Set this to your directory containing sources
      - /tmp:/tmp
    mem_limit: 128000m
    mem_reservation: 64000m
    command: cpggen --server --server-host 0.0.0.0 --server-port 7072
    environment:
      - JAVA_OPTS="-Xmx32G"
      - SL_CPG_OPTS="-J-Xms16g -J-Xmx32g"
      - SHIFTLEFT_JAVA_OPTS="-Xms16g -Xmx32g"
  joern:
    image: ghcr.io/appthreat/cpggen:main # change this to joern once it's live
    ports:
      - "9000:9000"
    volumes:
      - /home/almalinux/work:/app # Set this to your directory containing sources
      - /tmp:/tmp
    mem_limit: 128000m
    mem_reservation: 64000m
    command: joern -J-Xmx32g --server --server-host 0.0.0.0 --server-port 9000 --server-auth-username admin --server-auth-password admin
    environment:
      - JOERN_DATAFLOW_TRACKED_WIDTH=128
  polynote:
    build:
      dockerfile: contrib/polynote/Dockerfile
      labels:
        com.docker.compose.container-number: "2"
    # image: ghcr.io/appthreat/polynote
    volumes:
      - ./contrib/polynote/notebooks:/opt/notebooks # Set this to your notebook directory
      - ./contrib/polynote/config.yml:/opt/config/config.yml
      - /tmp:/tmp
      - ./:/opt/joern_lib
    ports:
      - "8192:8192"
    command: --config /opt/config/config.yml
