version: "3.9"
services:
  atomgen:
    image: ghcr.io/appthreat/atomgen:main
    ports:
      - "7073:7073"
    volumes:
      - $HOME:/app # Set this to your directory containing sources
      - /tmp:/tmp
    command: --server --server-host 0.0.0.0 --server-port 7073
    environment:
      - AT_DEBUG_MODE=debug
      - CPGGEN_MEMORY=4G
  cpggen:
    image: ghcr.io/appthreat/cpggen:main
    ports:
      - "7072:7072"
    volumes:
      - $HOME:/app # Set this to your directory containing sources
      - /tmp:/tmp
    command: cpggen --server --server-host 0.0.0.0 --server-port 7072
    environment:
      - AT_DEBUG_MODE=debug
      - CPGGEN_MEMORY=4G
  joern:
    image: ghcr.io/appthreat/cpggen:main
    ports:
      - "9000:9000"
    volumes:
      - $HOME:/app # Set this to your directory containing sources
      - /tmp:/tmp
    command: joern --server --server-host 0.0.0.0 --server-port 9000 --server-auth-username admin --server-auth-password admin
    environment:
      - JOERN_DATAFLOW_TRACKED_WIDTH=128
  polynote:
    build:
      dockerfile: contrib/polynote/Dockerfile
      labels:
        com.docker.compose.container-number: "2"
    # image: ghcr.io/appthreat/polynote:main
    volumes:
      - ./contrib/polynote/notebooks:/opt/notebooks # Set this to your notebook directory
      - ./contrib/polynote/config.yml:/opt/config/config.yml
      - /tmp:/tmp
      - ./:/opt/joern_lib
    ports:
      - "8192:8192"
    command: --config /opt/config/config.yml
