import json
import os

import pytest

from joern_lib.utils import print_flows, print_table

TEST_JAVA_HTTP_JSON = [
    {
        "_1": {
            "name": "home",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.home:java.lang.String(org.springframework.ui.Model,javax.servlet.http.HttpSession)",
            "signature": "java.lang.String(org.springframework.ui.Model,javax.servlet.http.HttpSession)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 50,
            "_label": "METHOD",
            "code": "public String home(Model model, HttpSession session)",
            "isExternal": False,
            "lineNumber": 46,
            "id": 112,
            "order": 3,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping(value = { "/", "/home" })',
                "columnNumber": 2,
                "order": 7,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 46,
                "id": 127,
            }
        ],
    },
    {
        "_1": {
            "name": "login",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.login:java.lang.String(org.springframework.ui.Model)",
            "signature": "java.lang.String(org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 55,
            "_label": "METHOD",
            "code": "public String login(Model model)",
            "isExternal": False,
            "lineNumber": 52,
            "id": 134,
            "order": 4,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/login")',
                "columnNumber": 2,
                "order": 6,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 52,
                "id": 142,
            }
        ],
    },
    {
        "_1": {
            "name": "login",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.login:java.lang.String(javax.servlet.http.HttpSession,java.lang.String,java.lang.String,org.springframework.ui.Model)",
            "signature": "java.lang.String(javax.servlet.http.HttpSession,java.lang.String,java.lang.String,org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 67,
            "_label": "METHOD",
            "code": 'public String login(HttpSession session, @RequestParam(name = "username", required = true) String username, @RequestParam(name = "password", required = true) String password, Model model)',
            "isExternal": False,
            "lineNumber": 57,
            "id": 147,
            "order": 5,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "PostMapping",
                "code": '@PostMapping("/login")',
                "columnNumber": 2,
                "order": 9,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.PostMapping",
                "lineNumber": 57,
                "id": 200,
            }
        ],
    },
    {
        "_1": {
            "name": "logout",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.logout:java.lang.String(javax.servlet.http.HttpSession)",
            "signature": "java.lang.String(javax.servlet.http.HttpSession)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 89,
            "_label": "METHOD",
            "code": "public String logout(HttpSession session)",
            "isExternal": False,
            "lineNumber": 85,
            "id": 253,
            "order": 7,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/logout")',
                "columnNumber": 2,
                "order": 6,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 85,
                "id": 263,
            }
        ],
    },
    {
        "_1": {
            "name": "update",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.update:java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
            "signature": "java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 100,
            "_label": "METHOD",
            "code": "public String update(HttpSession session, Model model)",
            "isExternal": False,
            "lineNumber": 91,
            "id": 268,
            "order": 8,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/update")',
                "columnNumber": 2,
                "order": 7,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 91,
                "id": 300,
            }
        ],
    },
    {
        "_1": {
            "name": "update",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.update:java.lang.String(javax.servlet.http.HttpSession,java.lang.String,org.springframework.ui.Model)",
            "signature": "java.lang.String(javax.servlet.http.HttpSession,java.lang.String,org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 115,
            "_label": "METHOD",
            "code": 'public String update(HttpSession session, @RequestParam(name = "newname") String newName, Model model)',
            "isExternal": False,
            "lineNumber": 102,
            "id": 305,
            "order": 9,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "PostMapping",
                "code": '@PostMapping("/update")',
                "columnNumber": 2,
                "order": 8,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.PostMapping",
                "lineNumber": 102,
                "id": 374,
            }
        ],
    },
    {
        "_1": {
            "name": "checkDB",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.checkDB:java.lang.String(java.lang.String,org.springframework.ui.Model)",
            "signature": "java.lang.String(java.lang.String,org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 133,
            "_label": "METHOD",
            "code": 'public String checkDB(@RequestParam(name = "dbpath") String dbpath, Model model) throws MalformedURLException, IOException',
            "isExternal": False,
            "lineNumber": 117,
            "id": 379,
            "order": 10,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "PostMapping",
                "code": '@PostMapping("/checkdb")',
                "columnNumber": 2,
                "order": 7,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.PostMapping",
                "lineNumber": 117,
                "id": 458,
            },
            {
                "name": "ResponseBody",
                "code": "@ResponseBody",
                "columnNumber": 2,
                "order": 8,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.ResponseBody",
                "lineNumber": 118,
                "id": 462,
            },
        ],
    },
    {
        "_1": {
            "name": "checkDB",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.checkDB:java.lang.String()",
            "signature": "java.lang.String()",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 138,
            "_label": "METHOD",
            "code": "public String checkDB()",
            "isExternal": False,
            "lineNumber": 135,
            "id": 464,
            "order": 11,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/checkdb")',
                "columnNumber": 2,
                "order": 5,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 135,
                "id": 471,
            }
        ],
    },
    {
        "_1": {
            "name": "transfer",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.transfer:java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
            "signature": "java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 149,
            "_label": "METHOD",
            "code": "public String transfer(HttpSession session, Model model)",
            "isExternal": False,
            "lineNumber": 140,
            "id": 476,
            "order": 12,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/transfer")',
                "columnNumber": 2,
                "order": 7,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 140,
                "id": 514,
            }
        ],
    },
    {
        "_1": {
            "name": "transfer",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.transfer:java.lang.String(javax.servlet.http.HttpSession,java.lang.String,java.lang.Float,org.springframework.ui.Model)",
            "signature": "java.lang.String(javax.servlet.http.HttpSession,java.lang.String,java.lang.Float,org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 219,
            "_label": "METHOD",
            "code": 'public String transfer(HttpSession session, @RequestParam(name = "toaccount") String toAccount, @RequestParam(name = "amount") Float amount, Model model)',
            "isExternal": False,
            "lineNumber": 152,
            "id": 519,
            "order": 13,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "Transactional",
                "code": "@Transactional",
                "columnNumber": 2,
                "order": 9,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.transaction.annotation.Transactional",
                "lineNumber": 152,
                "id": 767,
            },
            {
                "name": "PostMapping",
                "code": '@PostMapping("/transfer")',
                "columnNumber": 2,
                "order": 10,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.PostMapping",
                "lineNumber": 153,
                "id": 768,
            },
        ],
    },
    {
        "_1": {
            "name": "issue",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.issue:java.lang.String(org.springframework.ui.Model)",
            "signature": "java.lang.String(org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 224,
            "_label": "METHOD",
            "code": "public String issue(Model model)",
            "isExternal": False,
            "lineNumber": 221,
            "id": 773,
            "order": 14,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/issue")',
                "columnNumber": 2,
                "order": 6,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 221,
                "id": 781,
            }
        ],
    },
    {
        "_1": {
            "name": "issue",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.issue:java.lang.String(org.springframework.ui.Model,java.lang.String)",
            "signature": "java.lang.String(org.springframework.ui.Model,java.lang.String)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 239,
            "_label": "METHOD",
            "code": "public String issue(Model model, @RequestBody String body) throws ParserConfigurationException, SAXException, IOException",
            "isExternal": False,
            "lineNumber": 226,
            "id": 786,
            "order": 15,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "PostMapping",
                "code": '@PostMapping(value = "/issue", consumes = MediaType.APPLICATION_XML_VALUE)',
                "columnNumber": 2,
                "order": 7,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.PostMapping",
                "lineNumber": 226,
                "id": 850,
            }
        ],
    },
    {
        "_1": {
            "name": "support",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.support:java.lang.String(java.lang.String)",
            "signature": "java.lang.String(java.lang.String)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 265,
            "_label": "METHOD",
            "code": "public String support(@RequestParam(required = false) String desk)",
            "isExternal": False,
            "lineNumber": 258,
            "id": 928,
            "order": 17,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/support")',
                "columnNumber": 2,
                "order": 6,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 258,
                "id": 952,
            }
        ],
    },
    {
        "_1": {
            "name": "support",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.support:java.lang.String(org.springframework.ui.Model)",
            "signature": "java.lang.String(org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 272,
            "_label": "METHOD",
            "code": "public String support(Model model)",
            "isExternal": False,
            "lineNumber": 267,
            "id": 957,
            "order": 18,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/support/*")',
                "columnNumber": 2,
                "order": 6,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 267,
                "id": 969,
            }
        ],
    },
    {
        "_1": {
            "name": "jwt",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.jwt:java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
            "signature": "java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 284,
            "_label": "METHOD",
            "code": "public String jwt(HttpSession session, Model model)",
            "isExternal": False,
            "lineNumber": 274,
            "id": 974,
            "order": 19,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/token")',
                "columnNumber": 2,
                "order": 7,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 274,
                "id": 1019,
            }
        ],
    },
    {
        "_1": {
            "name": "jwt",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.jwt:java.lang.String(org.springframework.ui.Model,java.lang.String,javax.servlet.http.HttpSession)",
            "signature": "java.lang.String(org.springframework.ui.Model,java.lang.String,javax.servlet.http.HttpSession)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 298,
            "_label": "METHOD",
            "code": "public String jwt(Model model, @RequestParam String jwtString, HttpSession session)",
            "isExternal": False,
            "lineNumber": 286,
            "id": 1024,
            "order": 20,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "PostMapping",
                "code": '@PostMapping("/token")',
                "columnNumber": 2,
                "order": 8,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.PostMapping",
                "lineNumber": 286,
                "id": 1067,
            }
        ],
    },
    {
        "_1": {
            "name": "addressValidation",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.addressValidation:java.lang.String(org.springframework.ui.Model)",
            "signature": "java.lang.String(org.springframework.ui.Model)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 311,
            "_label": "METHOD",
            "code": "public String addressValidation(Model model) throws IOException",
            "isExternal": False,
            "lineNumber": 300,
            "id": 1072,
            "order": 21,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "GetMapping",
                "code": '@GetMapping("/address")',
                "columnNumber": 2,
                "order": 6,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.GetMapping",
                "lineNumber": 300,
                "id": 1112,
            }
        ],
    },
    {
        "_1": {
            "name": "addressValidation",
            "astParentFullName": "<empty>",
            "columnNumberEnd": 2,
            "fullName": "com.example.vulnspring.WebController.addressValidation:java.lang.String(org.springframework.ui.Model,java.lang.String)",
            "signature": "java.lang.String(org.springframework.ui.Model,java.lang.String)",
            "astParentType": "<empty>",
            "columnNumber": 2,
            "lineNumberEnd": 331,
            "_label": "METHOD",
            "code": "public String addressValidation(Model model, @RequestParam String encodedString)",
            "isExternal": False,
            "lineNumber": 313,
            "id": 1117,
            "order": 22,
            "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
        },
        "_2": [
            {
                "name": "PostMapping",
                "code": '@PostMapping("/address")',
                "columnNumber": 2,
                "order": 7,
                "_label": "ANNOTATION",
                "argumentIndex": -1,
                "fullName": "org.springframework.web.bind.annotation.PostMapping",
                "lineNumber": 313,
                "id": 1176,
            }
        ],
    },
]

TEST_JAVA_METHODS = [
    {
        "name": "main",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.VulnSpringApplication.main:void(java.lang.String[])",
        "signature": "void(java.lang.String[])",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 11,
        "_label": "METHOD",
        "code": "public static void main(String[] args)",
        "isExternal": False,
        "lineNumber": 9,
        "id": 17,
        "order": 1,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/VulnSpringApplication.java",
    },
    {
        "name": "<init>",
        "astParentFullName": "<empty>",
        "fullName": "com.example.vulnspring.VulnSpringApplication.<init>:void()",
        "signature": "void()",
        "astParentType": "<empty>",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": False,
        "id": 30,
        "order": 2,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/VulnSpringApplication.java",
    },
    {
        "name": "home",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.home:java.lang.String(org.springframework.ui.Model,javax.servlet.http.HttpSession)",
        "signature": "java.lang.String(org.springframework.ui.Model,javax.servlet.http.HttpSession)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 50,
        "_label": "METHOD",
        "code": "public String home(Model model, HttpSession session)",
        "isExternal": False,
        "lineNumber": 46,
        "id": 112,
        "order": 3,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "login",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.login:java.lang.String(org.springframework.ui.Model)",
        "signature": "java.lang.String(org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 55,
        "_label": "METHOD",
        "code": "public String login(Model model)",
        "isExternal": False,
        "lineNumber": 52,
        "id": 134,
        "order": 4,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "login",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.login:java.lang.String(javax.servlet.http.HttpSession,java.lang.String,java.lang.String,org.springframework.ui.Model)",
        "signature": "java.lang.String(javax.servlet.http.HttpSession,java.lang.String,java.lang.String,org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 67,
        "_label": "METHOD",
        "code": 'public String login(HttpSession session, @RequestParam(name = "username", required = true) String username, @RequestParam(name = "password", required = true) String password, Model model)',
        "isExternal": False,
        "lineNumber": 57,
        "id": 147,
        "order": 5,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "loginSuccess",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.loginSuccess:boolean(java.lang.String,java.lang.String)",
        "signature": "boolean(java.lang.String,java.lang.String)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 83,
        "_label": "METHOD",
        "code": "private boolean loginSuccess(String username, String password)",
        "isExternal": False,
        "lineNumber": 69,
        "id": 205,
        "order": 6,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "logout",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.logout:java.lang.String(javax.servlet.http.HttpSession)",
        "signature": "java.lang.String(javax.servlet.http.HttpSession)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 89,
        "_label": "METHOD",
        "code": "public String logout(HttpSession session)",
        "isExternal": False,
        "lineNumber": 85,
        "id": 253,
        "order": 7,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "update",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.update:java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
        "signature": "java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 100,
        "_label": "METHOD",
        "code": "public String update(HttpSession session, Model model)",
        "isExternal": False,
        "lineNumber": 91,
        "id": 268,
        "order": 8,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "update",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.update:java.lang.String(javax.servlet.http.HttpSession,java.lang.String,org.springframework.ui.Model)",
        "signature": "java.lang.String(javax.servlet.http.HttpSession,java.lang.String,org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 115,
        "_label": "METHOD",
        "code": 'public String update(HttpSession session, @RequestParam(name = "newname") String newName, Model model)',
        "isExternal": False,
        "lineNumber": 102,
        "id": 305,
        "order": 9,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "checkDB",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.checkDB:java.lang.String(java.lang.String,org.springframework.ui.Model)",
        "signature": "java.lang.String(java.lang.String,org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 133,
        "_label": "METHOD",
        "code": 'public String checkDB(@RequestParam(name = "dbpath") String dbpath, Model model) throws MalformedURLException, IOException',
        "isExternal": False,
        "lineNumber": 117,
        "id": 379,
        "order": 10,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "checkDB",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.checkDB:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 138,
        "_label": "METHOD",
        "code": "public String checkDB()",
        "isExternal": False,
        "lineNumber": 135,
        "id": 464,
        "order": 11,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "transfer",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.transfer:java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
        "signature": "java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 149,
        "_label": "METHOD",
        "code": "public String transfer(HttpSession session, Model model)",
        "isExternal": False,
        "lineNumber": 140,
        "id": 476,
        "order": 12,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "transfer",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.transfer:java.lang.String(javax.servlet.http.HttpSession,java.lang.String,java.lang.Float,org.springframework.ui.Model)",
        "signature": "java.lang.String(javax.servlet.http.HttpSession,java.lang.String,java.lang.Float,org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 219,
        "_label": "METHOD",
        "code": 'public String transfer(HttpSession session, @RequestParam(name = "toaccount") String toAccount, @RequestParam(name = "amount") Float amount, Model model)',
        "isExternal": False,
        "lineNumber": 152,
        "id": 519,
        "order": 13,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "issue",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.issue:java.lang.String(org.springframework.ui.Model)",
        "signature": "java.lang.String(org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 224,
        "_label": "METHOD",
        "code": "public String issue(Model model)",
        "isExternal": False,
        "lineNumber": 221,
        "id": 773,
        "order": 14,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "issue",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.issue:java.lang.String(org.springframework.ui.Model,java.lang.String)",
        "signature": "java.lang.String(org.springframework.ui.Model,java.lang.String)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 239,
        "_label": "METHOD",
        "code": "public String issue(Model model, @RequestBody String body) throws ParserConfigurationException, SAXException, IOException",
        "isExternal": False,
        "lineNumber": 226,
        "id": 786,
        "order": 15,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "getNodeString",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.getNodeString:java.lang.StringBuffer(org.w3c.dom.Node,java.lang.StringBuffer)",
        "signature": "java.lang.StringBuffer(org.w3c.dom.Node,java.lang.StringBuffer)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 256,
        "_label": "METHOD",
        "code": "StringBuffer getNodeString(Node node, StringBuffer currentString)",
        "isExternal": False,
        "lineNumber": 241,
        "id": 857,
        "order": 16,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "support",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.support:java.lang.String(java.lang.String)",
        "signature": "java.lang.String(java.lang.String)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 265,
        "_label": "METHOD",
        "code": "public String support(@RequestParam(required = false) String desk)",
        "isExternal": False,
        "lineNumber": 258,
        "id": 928,
        "order": 17,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "support",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.support:java.lang.String(org.springframework.ui.Model)",
        "signature": "java.lang.String(org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 272,
        "_label": "METHOD",
        "code": "public String support(Model model)",
        "isExternal": False,
        "lineNumber": 267,
        "id": 957,
        "order": 18,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "jwt",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.jwt:java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
        "signature": "java.lang.String(javax.servlet.http.HttpSession,org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 284,
        "_label": "METHOD",
        "code": "public String jwt(HttpSession session, Model model)",
        "isExternal": False,
        "lineNumber": 274,
        "id": 974,
        "order": 19,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "jwt",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.jwt:java.lang.String(org.springframework.ui.Model,java.lang.String,javax.servlet.http.HttpSession)",
        "signature": "java.lang.String(org.springframework.ui.Model,java.lang.String,javax.servlet.http.HttpSession)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 298,
        "_label": "METHOD",
        "code": "public String jwt(Model model, @RequestParam String jwtString, HttpSession session)",
        "isExternal": False,
        "lineNumber": 286,
        "id": 1024,
        "order": 20,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "addressValidation",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.addressValidation:java.lang.String(org.springframework.ui.Model)",
        "signature": "java.lang.String(org.springframework.ui.Model)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 311,
        "_label": "METHOD",
        "code": "public String addressValidation(Model model) throws IOException",
        "isExternal": False,
        "lineNumber": 300,
        "id": 1072,
        "order": 21,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "addressValidation",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.WebController.addressValidation:java.lang.String(org.springframework.ui.Model,java.lang.String)",
        "signature": "java.lang.String(org.springframework.ui.Model,java.lang.String)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 331,
        "_label": "METHOD",
        "code": "public String addressValidation(Model model, @RequestParam String encodedString)",
        "isExternal": False,
        "lineNumber": 313,
        "id": 1117,
        "order": 22,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "<init>",
        "astParentFullName": "<empty>",
        "fullName": "com.example.vulnspring.WebController.<init>:void()",
        "signature": "void()",
        "astParentType": "<empty>",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": False,
        "id": 1181,
        "order": 23,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "<clinit>",
        "astParentFullName": "<empty>",
        "fullName": "com.example.vulnspring.WebController.<clinit>:void()",
        "signature": "void()",
        "astParentType": "<empty>",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": False,
        "id": 1188,
        "order": 25,
        "filename": "<empty>",
    },
    {
        "name": "getStreetNumber",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.AddressDetails.getStreetNumber:int()",
        "signature": "int()",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 340,
        "_label": "METHOD",
        "code": "public int getStreetNumber()",
        "isExternal": False,
        "lineNumber": 338,
        "id": 1201,
        "order": 2,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "getStreetName",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.AddressDetails.getStreetName:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 344,
        "_label": "METHOD",
        "code": "public String getStreetName()",
        "isExternal": False,
        "lineNumber": 342,
        "id": 1211,
        "order": 3,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "<init>",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.AddressDetails.<init>:void(int,java.lang.String)",
        "signature": "void(int,java.lang.String)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 351,
        "_label": "METHOD",
        "code": "AddressDetails(int streetNumber, String streetName)",
        "isExternal": False,
        "lineNumber": 348,
        "id": 1222,
        "order": 5,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "toString",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.AddressDetails.toString:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 356,
        "_label": "METHOD",
        "code": "public String toString()",
        "isExternal": False,
        "lineNumber": 353,
        "id": 1236,
        "order": 6,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/WebController.java",
    },
    {
        "name": "doFilter",
        "astParentFullName": "<empty>",
        "columnNumberEnd": 2,
        "fullName": "com.example.vulnspring.SessionFilter.doFilter:void(javax.servlet.ServletRequest,javax.servlet.ServletResponse,javax.servlet.FilterChain)",
        "signature": "void(javax.servlet.ServletRequest,javax.servlet.ServletResponse,javax.servlet.FilterChain)",
        "astParentType": "<empty>",
        "columnNumber": 2,
        "lineNumberEnd": 40,
        "_label": "METHOD",
        "code": "public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException",
        "isExternal": False,
        "lineNumber": 23,
        "id": 1306,
        "order": 2,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/SessionFilter.java",
    },
    {
        "name": "<init>",
        "astParentFullName": "<empty>",
        "fullName": "com.example.vulnspring.SessionFilter.<init>:void()",
        "signature": "void()",
        "astParentType": "<empty>",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": False,
        "id": 1379,
        "order": 3,
        "filename": "/home/almalinux/work/sandbox/vuln-spring/src/main/java/com/example/vulnspring/SessionFilter.java",
    },
    {
        "name": "<clinit>",
        "astParentFullName": "<empty>",
        "fullName": "com.example.vulnspring.SessionFilter.<clinit>:void()",
        "signature": "void()",
        "astParentType": "<empty>",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": False,
        "id": 1391,
        "order": 6,
        "filename": "<empty>",
    },
    {
        "name": "run",
        "astParentFullName": "org.springframework.boot.SpringApplication",
        "fullName": "org.springframework.boot.SpringApplication.run:org.springframework.context.ConfigurableApplicationContext(java.lang.Class,java.lang.String[])",
        "signature": "org.springframework.context.ConfigurableApplicationContext(java.lang.Class,java.lang.String[])",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1584,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "addAttribute",
        "astParentFullName": "org.springframework.ui.Model",
        "fullName": "org.springframework.ui.Model.addAttribute:org.springframework.ui.Model(java.lang.String,java.lang.Object)",
        "signature": "org.springframework.ui.Model(java.lang.String,java.lang.Object)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1600,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getAttribute",
        "astParentFullName": "javax.servlet.http.HttpSession",
        "fullName": "javax.servlet.http.HttpSession.getAttribute:java.lang.Object(java.lang.String)",
        "signature": "java.lang.Object(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1607,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "debug",
        "astParentFullName": "org.slf4j.Logger",
        "fullName": "org.slf4j.Logger.debug:void(java.lang.String)",
        "signature": "void(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1613,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "setAttribute",
        "astParentFullName": "javax.servlet.http.HttpSession",
        "fullName": "javax.servlet.http.HttpSession.setAttribute:void(java.lang.String,java.lang.Object)",
        "signature": "void(java.lang.String,java.lang.Object)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1624,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "queryForMap",
        "astParentFullName": "org.springframework.jdbc.core.JdbcTemplate",
        "fullName": "org.springframework.jdbc.core.JdbcTemplate.queryForMap:java.util.Map(java.lang.String,java.lang.Object[])",
        "signature": "java.util.Map(java.lang.String,java.lang.Object[])",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1646,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "containsKey",
        "astParentFullName": "java.util.Map",
        "fullName": "java.util.Map.containsKey:boolean(java.lang.Object)",
        "signature": "boolean(java.lang.Object)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1653,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "invalidate",
        "astParentFullName": "javax.servlet.http.HttpSession",
        "fullName": "javax.servlet.http.HttpSession.invalidate:void()",
        "signature": "void()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1659,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "get",
        "astParentFullName": "java.util.Map",
        "fullName": "java.util.Map.get:java.lang.Object(java.lang.Object)",
        "signature": "java.lang.Object(java.lang.Object)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1664,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "update",
        "astParentFullName": "org.springframework.jdbc.core.JdbcTemplate",
        "fullName": "org.springframework.jdbc.core.JdbcTemplate.update:int(java.lang.String,java.lang.Object[])",
        "signature": "int(java.lang.String,java.lang.Object[])",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1670,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "info",
        "astParentFullName": "org.slf4j.Logger",
        "fullName": "org.slf4j.Logger.info:void(java.lang.String)",
        "signature": "void(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1677,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "valueOf",
        "astParentFullName": "java.lang.String",
        "fullName": "java.lang.String.valueOf:java.lang.String(int)",
        "signature": "java.lang.String(int)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1683,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getBaseName",
        "astParentFullName": "org.apache.commons.io.FilenameUtils",
        "fullName": "org.apache.commons.io.FilenameUtils.getBaseName:java.lang.String(java.lang.String)",
        "signature": "java.lang.String(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1688,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "equalsIgnoreCase",
        "astParentFullName": "java.lang.String",
        "fullName": "java.lang.String.equalsIgnoreCase:boolean(java.lang.String)",
        "signature": "boolean(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1693,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "java.net.URL",
        "fullName": "java.net.URL.<init>:void(java.lang.String)",
        "signature": "void(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1702,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "next",
        "astParentFullName": "java.util.Scanner",
        "fullName": "java.util.Scanner.next:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1707,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "useDelimiter",
        "astParentFullName": "java.util.Scanner",
        "fullName": "java.util.Scanner.useDelimiter:java.util.Scanner(java.lang.String)",
        "signature": "java.util.Scanner(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1712,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "java.util.Scanner",
        "fullName": "java.util.Scanner.<init>:void(java.io.InputStream,java.lang.String)",
        "signature": "void(java.io.InputStream,java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1718,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "openStream",
        "astParentFullName": "java.net.URL",
        "fullName": "java.net.URL.openStream:java.io.InputStream()",
        "signature": "java.io.InputStream()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1724,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "copy",
        "astParentFullName": "org.apache.commons.io.IOUtils",
        "fullName": "org.apache.commons.io.IOUtils.copy:long(java.net.URL,java.io.File)",
        "signature": "long(java.net.URL,java.io.File)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1729,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "java.io.File",
        "fullName": "java.io.File.<init>:void(java.lang.String)",
        "signature": "void(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1735,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "valueOf",
        "astParentFullName": "java.lang.String",
        "fullName": "java.lang.String.valueOf:java.lang.String(java.lang.Object)",
        "signature": "java.lang.String(java.lang.Object)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1750,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "newInstance",
        "astParentFullName": "javax.xml.parsers.DocumentBuilderFactory",
        "fullName": "javax.xml.parsers.DocumentBuilderFactory.newInstance:javax.xml.parsers.DocumentBuilderFactory()",
        "signature": "javax.xml.parsers.DocumentBuilderFactory()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1765,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "newDocumentBuilder",
        "astParentFullName": "javax.xml.parsers.DocumentBuilderFactory",
        "fullName": "javax.xml.parsers.DocumentBuilderFactory.newDocumentBuilder:javax.xml.parsers.DocumentBuilder()",
        "signature": "javax.xml.parsers.DocumentBuilder()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1769,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "parse",
        "astParentFullName": "javax.xml",
        "fullName": "javax.xml.parsers.DocumentBuilder.parse:org.w3c.dom.Document(org.xml.sax.InputSource)",
        "signature": "org.w3c.dom.Document(org.xml.sax.InputSource)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1774,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "org.xml.sax.InputSource",
        "fullName": "org.xml.sax.InputSource.<init>:void(java.io.Reader)",
        "signature": "void(java.io.Reader)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1780,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "java.io.StringReader",
        "fullName": "java.io.StringReader.<init>:void(java.lang.String)",
        "signature": "void(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1785,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "toString",
        "astParentFullName": "java.lang.StringBuffer",
        "fullName": "java.lang.StringBuffer.toString:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1790,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getFirstChild",
        "astParentFullName": "org.w3c.dom.Document",
        "fullName": "org.w3c.dom.Document.getFirstChild:org.w3c.dom.Node()",
        "signature": "org.w3c.dom.Node()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1795,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "java.lang.StringBuffer",
        "fullName": "java.lang.StringBuffer.<init>:void()",
        "signature": "void()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1800,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getNodeName",
        "astParentFullName": "org.w3c.dom.Node",
        "fullName": "org.w3c.dom.Node.getNodeName:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1804,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "equals",
        "astParentFullName": "java.lang.String",
        "fullName": "java.lang.String.equals:boolean(java.lang.Object)",
        "signature": "boolean(java.lang.Object)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1809,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "trim",
        "astParentFullName": "java.lang.String",
        "fullName": "java.lang.String.trim:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1815,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getNodeValue",
        "astParentFullName": "org.w3c.dom.Node",
        "fullName": "org.w3c.dom.Node.getNodeValue:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1820,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "append",
        "astParentFullName": "java.lang.StringBuffer",
        "fullName": "java.lang.StringBuffer.append:java.lang.StringBuffer(java.lang.String)",
        "signature": "java.lang.StringBuffer(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1825,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getLength",
        "astParentFullName": "org.w3c.dom.NodeList",
        "fullName": "org.w3c.dom.NodeList.getLength:int()",
        "signature": "int()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1836,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getChildNodes",
        "astParentFullName": "org.w3c.dom.Node",
        "fullName": "org.w3c.dom.Node.getChildNodes:org.w3c.dom.NodeList()",
        "signature": "org.w3c.dom.NodeList()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1841,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "item",
        "astParentFullName": "org.w3c.dom.NodeList",
        "fullName": "org.w3c.dom.NodeList.item:org.w3c.dom.Node(int)",
        "signature": "org.w3c.dom.Node(int)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1850,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "none",
        "astParentFullName": "com.auth0.jwt.algorithms.Algorithm",
        "fullName": "com.auth0.jwt.algorithms.Algorithm.none:com.auth0.jwt.algorithms.Algorithm()",
        "signature": "com.auth0.jwt.algorithms.Algorithm()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1856,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "sign",
        "astParentFullName": "com.auth0.jwt.JWTCreator$Builder",
        "fullName": "com.auth0.jwt.JWTCreator$Builder.sign:java.lang.String(com.auth0.jwt.algorithms.Algorithm)",
        "signature": "java.lang.String(com.auth0.jwt.algorithms.Algorithm)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1860,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "withClaim",
        "astParentFullName": "com.auth0.jwt.JWTCreator$Builder",
        "fullName": "com.auth0.jwt.JWTCreator$Builder.withClaim:com.auth0.jwt.JWTCreator$Builder(java.lang.String,java.lang.String)",
        "signature": "com.auth0.jwt.JWTCreator$Builder(java.lang.String,java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1866,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "withIssuer",
        "astParentFullName": "com.auth0.jwt.JWTCreator$Builder",
        "fullName": "com.auth0.jwt.JWTCreator$Builder.withIssuer:com.auth0.jwt.JWTCreator$Builder(java.lang.String)",
        "signature": "com.auth0.jwt.JWTCreator$Builder(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1873,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "create",
        "astParentFullName": "com.auth0.jwt.JWT",
        "fullName": "com.auth0.jwt.JWT.create:com.auth0.jwt.JWTCreator$Builder()",
        "signature": "com.auth0.jwt.JWTCreator$Builder()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1879,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "decode",
        "astParentFullName": "com.auth0.jwt.JWT",
        "fullName": "com.auth0.jwt.JWT.decode:com.auth0.jwt.interfaces.DecodedJWT(java.lang.String)",
        "signature": "com.auth0.jwt.interfaces.DecodedJWT(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1883,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "asString",
        "astParentFullName": "com.auth0.jwt.interfaces.Claim",
        "fullName": "com.auth0.jwt.interfaces.Claim.asString:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1888,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getClaim",
        "astParentFullName": "com.auth0.jwt.interfaces.DecodedJWT",
        "fullName": "com.auth0.jwt.interfaces.DecodedJWT.getClaim:com.auth0.jwt.interfaces.Claim(java.lang.String)",
        "signature": "com.auth0.jwt.interfaces.Claim(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1893,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "java.io.ByteArrayOutputStream",
        "fullName": "java.io.ByteArrayOutputStream.<init>:void()",
        "signature": "void()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1899,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "java.io.ObjectOutputStream",
        "fullName": "java.io.ObjectOutputStream.<init>:void(java.io.OutputStream)",
        "signature": "void(java.io.OutputStream)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1903,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "writeObject",
        "astParentFullName": "java.io.ObjectOutputStream",
        "fullName": "java.io.ObjectOutputStream.writeObject:void(java.lang.Object)",
        "signature": "void(java.lang.Object)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1908,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "close",
        "astParentFullName": "java.io.ObjectOutputStream",
        "fullName": "java.io.ObjectOutputStream.close:void()",
        "signature": "void()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1914,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "encodeToString",
        "astParentFullName": "java.util.Base64$Encoder",
        "fullName": "java.util.Base64$Encoder.encodeToString:java.lang.String(byte[])",
        "signature": "java.lang.String(byte[])",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1919,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getEncoder",
        "astParentFullName": "java.util.Base64",
        "fullName": "java.util.Base64.getEncoder:java.util.Base64$Encoder()",
        "signature": "java.util.Base64$Encoder()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1925,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "toByteArray",
        "astParentFullName": "java.io.ByteArrayOutputStream",
        "fullName": "java.io.ByteArrayOutputStream.toByteArray:byte[]()",
        "signature": "byte[]()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1929,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "decode",
        "astParentFullName": "java.util.Base64$Decoder",
        "fullName": "java.util.Base64$Decoder.decode:byte[](java.lang.String)",
        "signature": "byte[](java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1934,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getDecoder",
        "astParentFullName": "java.util.Base64",
        "fullName": "java.util.Base64.getDecoder:java.util.Base64$Decoder()",
        "signature": "java.util.Base64$Decoder()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1940,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "java.io.ObjectInputStream",
        "fullName": "java.io.ObjectInputStream.<init>:void(java.io.InputStream)",
        "signature": "void(java.io.InputStream)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1944,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "<init>",
        "astParentFullName": "java.io.ByteArrayInputStream",
        "fullName": "java.io.ByteArrayInputStream.<init>:void(byte[])",
        "signature": "void(byte[])",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1949,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "readObject",
        "astParentFullName": "java.io.ObjectInputStream",
        "fullName": "java.io.ObjectInputStream.readObject:java.lang.Object()",
        "signature": "java.lang.Object()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1954,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "close",
        "astParentFullName": "java.io.ObjectInputStream",
        "fullName": "java.io.ObjectInputStream.close:void()",
        "signature": "void()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1959,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "printStackTrace",
        "astParentFullName": "java.io.IOException",
        "fullName": "java.io.IOException.printStackTrace:void()",
        "signature": "void()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1964,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "printStackTrace",
        "astParentFullName": "java.lang.ClassNotFoundException",
        "fullName": "java.lang.ClassNotFoundException.printStackTrace:void()",
        "signature": "void()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1969,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getLogger",
        "astParentFullName": "org.slf4j.LoggerFactory",
        "fullName": "org.slf4j.LoggerFactory.getLogger:org.slf4j.Logger(java.lang.Class)",
        "signature": "org.slf4j.Logger(java.lang.Class)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1974,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getSession",
        "astParentFullName": "javax.servlet.http.HttpServletRequest",
        "fullName": "javax.servlet.http.HttpServletRequest.getSession:javax.servlet.http.HttpSession()",
        "signature": "javax.servlet.http.HttpSession()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1979,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getMethod",
        "astParentFullName": "javax.servlet.http.HttpServletRequest",
        "fullName": "javax.servlet.http.HttpServletRequest.getMethod:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1984,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "getServletPath",
        "astParentFullName": "javax.servlet.http.HttpServletRequest",
        "fullName": "javax.servlet.http.HttpServletRequest.getServletPath:java.lang.String()",
        "signature": "java.lang.String()",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1989,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "matches",
        "astParentFullName": "java.lang.String",
        "fullName": "java.lang.String.matches:boolean(java.lang.String)",
        "signature": "boolean(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 1994,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "doFilter",
        "astParentFullName": "javax.servlet.FilterChain",
        "fullName": "javax.servlet.FilterChain.doFilter:void(javax.servlet.ServletRequest,javax.servlet.ServletResponse)",
        "signature": "void(javax.servlet.ServletRequest,javax.servlet.ServletResponse)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 2000,
        "order": 0,
        "filename": "<empty>",
    },
    {
        "name": "sendRedirect",
        "astParentFullName": "javax.servlet.http.HttpServletResponse",
        "fullName": "javax.servlet.http.HttpServletResponse.sendRedirect:void(java.lang.String)",
        "signature": "void(java.lang.String)",
        "astParentType": "TYPE_DECL",
        "_label": "METHOD",
        "code": "<empty>",
        "isExternal": True,
        "id": 2007,
        "order": 0,
        "filename": "<empty>",
    },
]


@pytest.fixture
def test_reach_data():
    return os.path.join(
        os.path.dirname(os.path.realpath(__file__)), "data", "reach.json"
    )


def test_java_http_routes():
    assert not print_table(TEST_JAVA_HTTP_JSON)


def test_java_methods():
    assert not print_table(TEST_JAVA_METHODS)


def test_reach_parsing(test_reach_data):
    with open(test_reach_data) as fp:
        assert not print_flows(json.load(fp))
