listen:
  host: 0.0.0.0

storage:
  dir: /opt/notebooks

dependencies:
  python:
    - GitPython
    - pandas
    - matplotlib
    - graphviz
    - pydotplus
    - networkx[default,extra]
    - file:///opt/joern_lib
env:
  AT_DEBUG_MODE: debug
