name: Upload Package and Container image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install and test
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          sudo apt install -y graphviz-dev
          poetry install --no-cache
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run pytest --cov=joern_lib tests
      - name: Release PyPI
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
